### ISSUE TITLE
torch-mesh-isect dependency problems

### ISSUE THREAD

**Issue by WilliamAshbee** [m-qiang/CortexODE#1]
Hey, in your requirements.txt file you commented out the # torch-mesh-isect dependency. 

I tracked it down to this github project:
https://github.com/vchoutas/torch-mesh-isect

I attempted to install from this, but have so far been unsuccessful, can you give advice on how to satisfy the torch-mesh-isect dependency? 

I was really impressed by your paper, and would like to work with your codebase if I can. Thanks. 
William Ashbee.

**Comment by m-qiang** [comment]
Hi William, thanks for your question. I suggest to take a look at the [https://github.com/vchoutas/torch-mesh-isect/issues]

**Comment by m-qiang** [comment]
Hi William, thanks for your question. 

To install the torch-mesh-isect library, I suggest to take a look at [https://github.com/vchoutas/torch-mesh-isect/issues](https://github.com/vchoutas/torch-mesh-isect/issues). I also encountered several problems when I installed it, and I found the solutions were helpful in the issues of their github repo. You might need to change a few lines of code (see issues #23, #26) depending on the problems you encountered in the installation.

Alternatively, the torch-mesh-isect library is only used to check mesh self-intersections in the evaluation. You can just comment out the related codes (lines 166-191) in  ```util/mesh.py```, so that you can run the training/testing without checking the self-intersections.

Hope these can help. Bests, Qiang.
